#!/usr/bin/env bash

set -e

export TEST_USER_ID=${TEST_USER_ID:-$(id -u)}
export TEST_GROUP_ID=${TEST_GROUP_ID:-$(id -g)}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

docker-compose -p jdb-tests $CMD
