#!/usr/bin/env bash

set -e

export APP_USER_ID=${APP_USER_ID:-$(id -u)}
export APP_GROUP_ID=${APP_GROUP_ID:-$(id -g)}
export PHP_VERSION=${PHP_VERSION:-8.1}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

if [ "$CMD" == "reset" ]; then
    # Stop/Remove containers
    docker compose -p jdb-tests rm -sf || true

    # Clean postgres volume
    docker volume rm "jdb_test_pg_data" || true
    docker volume rm "jdb_test_mysql_data" || true
    exit 0
fi

docker compose -p jdb-tests $CMD
